name: Run Tests

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"
    workflow_dispatch:

env:
    GH_TOKEN: ${{ secrets.NEW_PAT_SECRET }}

# Use concurrency to ensure only the latest run for a branch is in progress
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Run tests
              run: |
                  uv sync --dev

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Run Pytests
              run: |
                  uv run pytest tests/tests.py -s -vvv
