name: Example Workflow

on:
    push:
    workflow_dispatch:

env:
    GH_TOKEN: ${{ secrets.NEW_PAT_SECRET }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install ghchain
              run: |
                  pip install .[test]
                  pip install pytest

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit and Push
              run: |
                  cp ../mytest/.ghchain.toml ghchain/
                  cp ../mytest/.ghchain.toml .
                  pytest tests/tests.py -s -vvv
