# taken from https://github.com/ArjanCodes/bragir/blob/1f09637302486296020163a89c166a9c230fcae3/.github/workflows/update_changelog.yaml
name: Update Changelog Branch

on:
    workflow_run:
        workflows: ["setup_and_build"]
        types: [completed]

jobs:
    update_changelog:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Create Temporary Branch
              run: |
                  git checkout -b update-changelog-${{ github.event.release.name }}
                  echo "BRANCH_NAME=update-changelog-${{ github.event.release.name }}" >> $GITHUB_ENV

            - name: Update Changelog
              uses: stefanzweifel/changelog-updater-action@v1
              with:
                  release-notes: ${{ github.event.release.body }} # Add release notes to changelog
                  latest-version: ${{ github.event.release.name }} # Add latest version to changelog

            - name: Commit updated CHANGELOG
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: ${{ github.event.release.target_commitish }}
                  commit_message: Update Changelog for ${{ github.event.release.name }}
                  file_pattern: CHANGELOG.md

            - name: Push changes to temporary branch
              run: |
                  git push origin HEAD:$BRANCH_NAME

            - name: Create Pull Request
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh pr create \
                    --base main \
                    --head $BRANCH_NAME \
                    --title "Automated Pull Request from $BRANCH_NAME to main" \
                    --body "This is an automated pull request created via GitHub Actions."
